In [2]:
!pip install pandas numpy scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
df = pd.read_csv("tmdb_5000_movies.csv")
df.head()

      budget  ... vote_count
0  237000000  ...      11800
1  300000000  ...       4500
2  245000000  ...       4466
3  250000000  ...       9106
4  260000000  ...       2124

[5 rows x 20 columns]

In [7]:
df = df[["title", "overview"]]
df = df.dropna()
df.head()

                                      title                                           overview
0                                    Avatar  In the 22nd century, a paraplegic Marine is di...
1  Pirates of the Caribbean: At World's End  Captain Barbossa, long believed to be dead, ha...
2                                   Spectre  A cryptic message from Bond’s past sends him o...
3                     The Dark Knight Rises  Following the death of District Attorney Harve...
4                               John Carter  John Carter is a war-weary, former military ca...

In [8]:
tfidf = TfidfVectorizer(stop_words="english")
tfidf_matrix = tfidf.fit_transform(df["overview"])
tfidf_matrix.shape

(4800, 20978)

In [9]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [11]:
df = df.reset_index()

def recommend(movie_title, top_n=5):
  idx = df[df['title'] == movie_title].index[0]
  similarity_scores = list(enumerate(cosine_sim[idx]))
  similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
  similarity_scores = similarity_scores[1:top_n+1]
  movie_indices = [i[0] for i in similarity_scores]
  return df['title'].iloc[movie_indices]

In [12]:
recommend("Avatar")

3603               Apollo 18
2130            The American
634               The Matrix
1341    The Inhabited Island
529         Tears of the Sun
Name: title, dtype: object

In [14]:
df_full = pd.read_csv("tmdb_5000_movies.csv")
df_full.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [15]:
import ast

def extract_names(text):
  try:
    data = ast.literal_eval(text)
    return " ".join([i['name'] for i in data])
  except:
    return ""

df_full['genres'] = df_full['genres'].apply(extract_names)
df_full['keywords'] = df_full["keywords"].apply(extract_names)

In [17]:
df_full['overview'] = df_full['overview'].fillna("")

df_full['combined'] = (
    df_full['overview'] + " " +
    df_full['genres'] + " " +
    df_full['keywords']
)

df = df_full[['title', 'combined']]

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['combined'])

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [20]:
df = df.reset_index()

In [23]:
def recommend(movie_title, top_n=5):
  movie_title = movie_title.lower()

  matches = df[df['title'].str.lower() == movie_title]

  if matches.empty:
    return "Movie not found"

  idx = matches.index[0]

  similarity_scores = list(enumerate(cosine_sim[idx]))
  similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
  similarity_scores = similarity_scores[1:top_n+1]
  movie_indices = [i[0] for i in similarity_scores]
  return df['title'].iloc[movie_indices].tolist()

In [26]:
recommend("King Kong")

['Ed Wood',
 'Meet Dave',
 'Return to the Blue Lagoon',
 "America's Sweethearts",
 'The Blue Lagoon']

In [28]:
# AI Movie Recommendation System
## Data Preprocessing
## Feature Engineering
## Model Building
## Recommendation Function